welcome_message:
	.ascii "welcome to the number guessing game!\n"

tries_message_0:
	.ascii "you have "

tries_message_1:
	.ascii " tries to guess a number between 1 and 100.\n"

tries_message_1_last:
	.ascii " last try to guess a number between 1 and 100!\n"

number_prompt:
	.ascii "enter your guess: "

lose_message_0:
    .ascii "uh oh, you ran out of tries! the number was "

lose_message_1:
    .ascii "...\nbetter luck next time!\n"

low_message:
	.ascii "too low!\n"

high_message:
	.ascii "too high!\n"

invalid_message:
	.ascii "invalid number!\n"

win_message:
	.ascii "congratulations, you won!\n"
